//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottageCareOnlinePricing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalRoom
    {
        public long ID { get; set; }
        public Nullable<long> AdditionalRoomMasterID { get; set; }
        public long PlanID { get; set; }
        public string RoomDescription { get; set; }
        public decimal RoomPrice { get; set; }
    }
}
