//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottageCareOnlinePricing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleaningAppointment
    {
        public long Id { get; set; }
        public long GuestUserId { get; set; }
        public Nullable<System.DateTime> PrefferedDate1 { get; set; }
        public Nullable<System.DateTime> PrefferedDate2 { get; set; }
        public Nullable<System.DateTime> PrefferedDate3 { get; set; }
        public Nullable<bool> IsSoonestAvailable { get; set; }
        public bool PrefferedTime { get; set; }
        public string MethodOfEntry { get; set; }
        public Nullable<bool> IsFlexibleScheduling { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual GuestUser GuestUser { get; set; }
    }
}
