//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottageCareOnlinePricing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long CompanyID { get; set; }
        public System.Guid GUID { get; set; }
        public string DatabaseName { get; set; }
        public string BusinessName { get; set; }
        public string BusinessID { get; set; }
        public Nullable<long> Timezone { get; set; }
        public string AllowedIp { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
    }
}
