//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottageCareOnlinePricing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDetail
    {
        public long Id { get; set; }
        public long GuestUserId { get; set; }
        public long QuoteId { get; set; }
        public string CleaningFrequency { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual GuestUser GuestUser { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
